include: package:pedantic/analysis_options.1.7.0.yaml

analyzer:
  exclude:
    - 'build/**'
    - 'doc/api/**'
    - 'last_prod/**'
    - 'lib/bower/**'
    - 'lib/services/_dartpadsupportservices.dart'
    - 'lib/services/dartservices.dart'
    - 'third_party/pkg/**'
